import { type Question } from './mbti-types'

export const QUESTIONS: Question[] = [
  // EI (30题) - 外向 (E) vs 内向 (I)
  { id: "q1", text: "在社交场合中，你通常是活跃分子，主动开启话题。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q2", text: "你更喜欢独自思考，而不是在群体中大声讨论。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q3", text: "长时间的社交活动会让你感到精力充沛，而不是疲惫。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q4", text: "你倾向于在开口说话前先在脑中完整构思好内容。", dimension: "EI", agree: "I", contexts: ["social", "personal"], socialRelevant: true },
  { id: "q5", text: "你喜欢成为众人关注的焦点。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q6", text: "在晚会上，你更愿意与少数几个熟悉的人深谈。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q7", text: "你更喜欢开放式的办公环境，方便随时与同事交流。", dimension: "EI", agree: "E", contexts: ["work"], workRelevant: true },
  { id: "q8", text: "工作时，你更希望有一个安静、独立且不被打扰的空间。", dimension: "EI", agree: "I", contexts: ["work"], workRelevant: true },
  { id: "q9", text: "你通常很容易结识新朋友。", dimension: "EI", agree: "E", contexts: ["general"] },
  { id: "q10", text: "你觉得独处是一种享受，甚至是一种充电方式。", dimension: "EI", agree: "I", contexts: ["general"] },
  { id: "q11", text: "你倾向于在群体中表现得很有存在感。", dimension: "EI", agree: "E", contexts: ["personal"] },
  { id: "q12", text: "你更愿意通过文字（如邮件或信息）而非电话来沟通。", dimension: "EI", agree: "I", contexts: ["personal"] },
  { id: "q13", text: "你喜欢参与热闹的项目，并从中获得能量。", dimension: "EI", agree: "E", contexts: ["work", "social"], workRelevant: true, socialRelevant: true },
  { id: "q14", text: "你往往需要一些时间来适应新的社交环境。", dimension: "EI", agree: "I", contexts: ["work", "social"], workRelevant: true, socialRelevant: true },
  { id: "q15", text: "你喜欢在聚会中四处走动，认识不同的人。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q16", text: "你通常不会主动发起闲聊。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q17", text: "你乐于分享自己的想法和经历。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q18", text: "你倾向于保留个人隐私，只对极少数人开放。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q19", text: "你觉得快节奏、充满互动的环境非常吸引人。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q20", text: "你更享受深度思考，即使这会让你看起来有点沉默。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q21", text: "你喜欢在团队中带头讨论问题。", dimension: "EI", agree: "E", contexts: ["work", "social"], workRelevant: true, socialRelevant: true },
  { id: "q22", text: "你更愿意在幕后工作，不希望太受关注。", dimension: "EI", agree: "I", contexts: ["work"], workRelevant: true },
  { id: "q23", text: "你觉得通过社交来缓解压力是非常有效的方式。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q24", text: "你觉得过多的外界刺激会让你感到不知所措。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q25", text: "你倾向于表达而非倾听。", dimension: "EI", agree: "E", contexts: ["general"] },
  { id: "q26", text: "你是一个深思熟虑的人，不急于发表意见。", dimension: "EI", agree: "I", contexts: ["general"] },
  { id: "q27", text: "你喜欢在行动中思考，而不是行动前先想清楚。", dimension: "EI", agree: "E", contexts: ["personal"] },
  { id: "q28", text: "你更喜欢一对一的交流，而非大群体互动。", dimension: "EI", agree: "I", contexts: ["personal"] },
  { id: "q29", text: "你在公众场合通常表现得自信且健谈。", dimension: "EI", agree: "E", contexts: ["general"] },
  { id: "q30", text: "你往往需要时间独处来整理思绪。", dimension: "EI", agree: "I", contexts: ["personal"] },

  // SN (30题) - 感觉 (S) vs 直觉 (N)
  { id: "q31", text: "你非常注重细节，能够敏锐地观察到环境的变化。", dimension: "SN", agree: "S", contexts: ["work"], workRelevant: true },
  { id: "q32", text: "你更关注事物背后的深远含义和未来的可能性。", dimension: "SN", agree: "N", contexts: ["general"] },
  { id: "q33", text: "你更喜欢处理具体、可见的事实，而非抽象的理论。", dimension: "SN", agree: "S", contexts: ["work"], workRelevant: true },
  { id: "q34", text: "你经常会有一些天马行空、充满创造力的想法。", dimension: "SN", agree: "N", contexts: ["general"] },
  { id: "q35", text: "你信任过去的经验，并倾向于按部就班地做事。", dimension: "SN", agree: "S", contexts: ["general"] },
  { id: "q36", text: "你很容易跳出固有思维模式，去尝试全新的方法。", dimension: "SN", agree: "N", contexts: ["work"], workRelevant: true },
  { id: "q37", text: "你更喜欢务实的人，而不是那些总是在幻象中度日的人。", dimension: "SN", agree: "S" },
  { id: "q38", text: "你常常对哲学、象征或未来的愿景产生浓厚兴趣。", dimension: "SN", agree: "N" },
  { id: "q39", text: "你更倾向于生活在当下，关注眼前的现实。", dimension: "SN", agree: "S" },
  { id: "q40", text: "你总是能预见到事情可能的发展方向，即使还没有任何征兆。", dimension: "SN", agree: "N" },
  { id: "q41", text: "你喜欢明确、清晰的指令和具体的执行计划。", dimension: "SN", agree: "S" },
  { id: "q42", text: "你觉得常规和重复的工作会让你感到无聊透顶。", dimension: "SN", agree: "N" },
  { id: "q43", text: "你关注证据和数据，不喜欢毫无依据的猜测。", dimension: "SN", agree: "S" },
  { id: "q44", text: "你喜欢使用比喻或联想的方式来表达自己的观点。", dimension: "SN", agree: "N" },
  { id: "q45", text: "你认为“脚踏实地”比“远见卓识”更重要。", dimension: "SN", agree: "S" },
  { id: "q46", text: "你经常会思考“如果……会怎样？”这类不切实际的问题。", dimension: "SN", agree: "N" },
  { id: "q47", text: "你更看重事实的准确性，甚至到了有点死板的程度。", dimension: "SN", agree: "S" },
  { id: "q48", text: "你更看重灵感和直觉，即使它们看起来不合逻辑。", dimension: "SN", agree: "N" },
  { id: "q49", text: "你喜欢学习那些可以直接应用到生活中的技能。", dimension: "SN", agree: "S" },
  { id: "q50", text: "你喜欢探索复杂的理论，即使它们暂时没有实际用途。", dimension: "SN", agree: "N" },
  { id: "q51", text: "你更倾向于按照说明书来操作复杂的设备。", dimension: "SN", agree: "S" },
  { id: "q52", text: "你通常能从碎片化的信息中拼凑出完整的大局观。", dimension: "SN", agree: "N" },
  { id: "q53", text: "你更喜欢处理日常琐事，而不是进行宏观规划。", dimension: "SN", agree: "S" },
  { id: "q54", text: "你觉得未来的无限可能性比当下的成就更让你兴奋。", dimension: "SN", agree: "N" },
  { id: "q55", text: "你倾向于描述事物的具体外观和细节。", dimension: "SN", agree: "S" },
  { id: "q56", text: "你倾向于寻找事物之间的关联性和隐藏模式。", dimension: "SN", agree: "N" },
  { id: "q57", text: "你对新奇但未经证实的理论持怀疑态度。", dimension: "SN", agree: "S" },
  { id: "q58", text: "你经常觉得自己的思想超前于大多数人。", dimension: "SN", agree: "N" },
  { id: "q59", text: "你更喜欢循序渐进的教学方式。", dimension: "SN", agree: "S" },
  { id: "q60", text: "你喜欢跳跃式的思维，经常能想到意想不到的切入点。", dimension: "SN", agree: "N" },

  // TF (30题) - 思考 (T) vs 情感 (F)
  { id: "q61", text: "在做决策时，你首先考虑逻辑和客观事实。", dimension: "TF", agree: "T" },
  { id: "q62", text: "在做决策时，你首先考虑他人的感受和价值观。", dimension: "TF", agree: "F" },
  { id: "q63", text: "你认为公平和客观比和谐与同情更重要。", dimension: "TF", agree: "T" },
  { id: "q64", text: "你愿意为了维护人际关系的和谐而做出妥协。", dimension: "TF", agree: "F" },
  { id: "q65", text: "当你批评他人时，你会直接指出对方的错误，而不带感情色彩。", dimension: "TF", agree: "T" },
  { id: "q66", text: "当你批评他人时，你会尽量委婉，以免伤害对方的感情。", dimension: "TF", agree: "F" },
  { id: "q67", text: "你更看重事情的结果和效率，而非过程中的情感体验。", dimension: "TF", agree: "T" },
  { id: "q68", text: "你认为关心他人、体察情绪是一个人最重要的品质。", dimension: "TF", agree: "F" },
  { id: "q69", text: "在争论中，你更关注逻辑是否严密，而不是对方是否尴尬。", dimension: "TF", agree: "T" },
  { id: "q70", text: "你很容易被感人的故事或他人的经历所触动。", dimension: "TF", agree: "F" },
  { id: "q71", text: "你更倾向于按照规则和标准来行事，不偏不倚。", dimension: "TF", agree: "T" },
  { id: "q72", text: "你认为规则应该是灵活的，应当根据具体情况体贴他人。", dimension: "TF", agree: "F" },
  { id: "q73", text: "你很难理解那些由于情绪波动而影响判断的人。", dimension: "TF", agree: "T" },
  { id: "q74", text: "你常常会设身处地地为他人着想。", dimension: "TF", agree: "F" },
  { id: "q75", text: "你认为“理性”是解决问题的唯一正确途径。", dimension: "TF", agree: "T" },
  { id: "q76", text: "你认为“同理心”在工作和生活中同样重要。", dimension: "TF", agree: "F" },
  { id: "q77", text: "即使真相令人难以接受，你也倾向于如实告知。", dimension: "TF", agree: "T" },
  { id: "q78", text: "为了避免伤害他人，你有时会选择“善意的谎言”。", dimension: "TF", agree: "F" },
  { id: "q79", text: "你更喜欢那些冷静、理智、甚至有些冷酷的人。", dimension: "TF", agree: "T" },
  { id: "q80", text: "你更喜欢那些热情、温暖、善解人意的人。", dimension: "TF", agree: "F" },
  { id: "q81", text: "你觉得分析复杂的问题非常有成就感。", dimension: "TF", agree: "T" },
  { id: "q82", text: "你觉得帮助他人解决情感困扰非常有意义。", dimension: "TF", agree: "F" },
  { id: "q83", text: "在工作中，你更倾向于根据绩效来奖惩，不讲情面。", dimension: "TF", agree: "T" },
  { id: "q84", text: "在工作中，你认为团队的凝聚力和成员的心情同样重要。", dimension: "TF", agree: "F" },
  { id: "q85", text: "你认为科学和逻辑能够解释世界上的一切。", dimension: "TF", agree: "T" },
  { id: "q86", text: "你相信有些东西（如爱和信仰）是无法用逻辑衡量的。", dimension: "TF", agree: "F" },
  { id: "q87", text: "你倾向于在头脑中构建严密的逻辑体系。", dimension: "TF", agree: "T" },
  { id: "q88", text: "你非常在意自己在他人心目中的形象和好感度。", dimension: "TF", agree: "F" },
  { id: "q89", text: "你更喜欢逻辑学或数学，而非心理学或艺术。", dimension: "TF", agree: "T" },
  { id: "q90", text: "你很容易觉察到周围人的情绪变化。", dimension: "TF", agree: "F" },

  // JP (30题) - 判断 (J) vs 感知 (P)
  { id: "q91", text: "你喜欢预先制定计划，并严格遵守时间表。", dimension: "JP", agree: "J" },
  { id: "q92", text: "你更喜欢随性而为，保持行程的灵活性。", dimension: "JP", agree: "P" },
  { id: "q93", text: "在开始一项任务前，你通常会先整理好桌面和环境。", dimension: "JP", agree: "J" },
  { id: "q94", text: "你觉得生活中的“条条框框”会限制你的自由和创造力。", dimension: "JP", agree: "P" },
  { id: "q95", text: "你倾向于尽早完成任务，而不是拖到最后期限。", dimension: "JP", agree: "J" },
  { id: "q96", text: "你在压力（如最后期限临近）下往往表现得更出色。", dimension: "JP", agree: "P" },
  { id: "q97", text: "你喜欢井然有序的环境，无法忍受杂乱。", dimension: "JP", agree: "J" },
  { id: "q98", text: "你经常开始新的兴趣或项目，但很难坚持到最后。", dimension: "JP", agree: "P" },
  { id: "q99", text: "你喜欢给所有事情下结论，不喜欢悬而未决的状态。", dimension: "JP", agree: "J" },
  { id: "q100", text: "你喜欢保留多种选项，等到最后一刻再做决定。", dimension: "JP", agree: "P" },
  { id: "q101", text: "你通常会提前订票或预定餐厅，而不是到了地方再说。", dimension: "JP", agree: "J" },
  { id: "q102", text: "你喜欢那种充满惊喜、不确定的旅行。", dimension: "JP", agree: "P" },
  { id: "q103", text: "你认为纪律是成功的基石。", dimension: "JP", agree: "J" },
  { id: "q104", text: "你更喜欢自由自在地工作，而不是受制于固定的流程。", dimension: "JP", agree: "P" },
  { id: "q105", text: "你总是能把东西放回原位。", dimension: "JP", agree: "J" },
  { id: "q106", text: "你的房间或桌面通常有点乱，但你能在乱中找到东西。", dimension: "JP", agree: "P" },
  { id: "q107", text: "你喜欢掌控全局，讨厌突发状况。", dimension: "JP", agree: "J" },
  { id: "q108", text: "你认为适应能力比计划能力更重要。", dimension: "JP", agree: "P" },
  { id: "q109", text: "你倾向于在做出决定后就不再更改。", dimension: "JP", agree: "J" },
  { id: "q110", text: "你经常会根据新的发现或灵感改变主意。", dimension: "JP", agree: "P" },
  { id: "q111", text: "你是一个非常有责任心、靠谱的人。", dimension: "JP", agree: "J" },
  { id: "q112", text: "你经常觉得计划赶不上变化，干脆就不计划了。", dimension: "JP", agree: "P" },
  { id: "q113", text: "你喜欢把生活和工作分得清清楚楚。", dimension: "JP", agree: "J" },
  { id: "q114", text: "你经常会同时进行好几个任务，并觉得这很有趣。", dimension: "JP", agree: "P" },
  { id: "q115", text: "你认为规则是为了让事情更高效、更可控。", dimension: "JP", agree: "J" },
  { id: "q116", text: "你经常被认为是一个“比较随和”或“爱玩”的人。", dimension: "JP", agree: "P" },
  { id: "q117", text: "你喜欢在任务清单上打勾的感觉。", dimension: "JP", agree: "J" },
  { id: "q118", text: "你更喜欢探索过程，而非最终的结果。", dimension: "JP", agree: "P" },
  { id: "q119", text: "你更喜欢按部就班的系统化工作。", dimension: "JP", agree: "J" },
  { id: "q120", text: "你更喜欢探索未知的、模糊的领域。", dimension: "JP", agree: "P" },
]
