import { type Question } from './mbti-types'

export const QUESTIONS: Question[] = [
  // EI (30 questions) - Extraversion (E) vs Introversion (I)
  { id: "q1", text: "社交的な場では、あなたは通常、積極的に会話を始めます。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q2", text: "グループで大声で議論するよりも、一人で考えることを好みます。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q3", text: "長時間の社交活動は疲れるどころか、活力を与えてくれます。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q4", text: "あなたは話す前に、言いたいことを頭の中で完全に組み立てる傾向があります。", dimension: "EI", agree: "I", contexts: ["social", "personal"], socialRelevant: true },
  { id: "q5", text: "あなたは注目の的になることが好きです。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q6", text: "パーティーでは、数人の知り合いと深い話をすることを好みます。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q7", text: "同僚と簡単にコミュニケーションできるオープンなオフィス環境を好みます。", dimension: "EI", agree: "E", contexts: ["work"], workRelevant: true },
  { id: "q8", text: "職場では、静かで独立した、誰にも邪魔されない空間を好みます。", dimension: "EI", agree: "I", contexts: ["work"], workRelevant: true },
  { id: "q9", text: "通常、新しい友達は簡単にできます。", dimension: "EI", agree: "E", contexts: ["general"] },
  { id: "q10", text: "あなたは孤独を楽しいと感じ、充電さえします。", dimension: "EI", agree: "I", contexts: ["general"] },
  { id: "q11", text: "あなたは集団の中で目立つ傾向があります。", dimension: "EI", agree: "E", contexts: ["personal"] },
  { id: "q12", text: "電話よりもテキスト (電子メールまたはメッセージ) でコミュニケーションをとることを好みます。", dimension: "EI", agree: "I", contexts: ["personal"] },
  { id: "q13", text: "あなたは活発なプロジェクトに参加するのが好きで、そこからエネルギーを得ることができます。", dimension: "EI", agree: "E", contexts: ["work", "social"], workRelevant: true, socialRelevant: true },
  { id: "q14", text: "新しい社会環境に適応するには時間がかかることがよくあります。", dimension: "EI", agree: "I", contexts: ["work", "social"], workRelevant: true, socialRelevant: true },
  { id: "q15", text: "あなたは、さまざまな人に会うために集まりの中で動き回るのが好きです。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q16", text: "あなたは通常、雑談を始めません。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q17", text: "自分の考えや経験を共有することを楽しんでいます。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q18", text: "あなたは個人のプライバシーを守り、少数の人にしか心を開かない傾向があります。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q19", text: "あなたは、ペースが速く、高度にインタラクティブな環境が非常に魅力的であると感じます。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q20", text: "たとえそれが少し静かに見えるとしても、あなたは深く考えることを好みます。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q21", text: "あなたはチーム内でディスカッションを主導することが好きです。", dimension: "EI", agree: "E", contexts: ["work", "social"], workRelevant: true, socialRelevant: true },
  { id: "q22", text: "あなたは舞台裏で働き、気づかれないことを好みます。", dimension: "EI", agree: "I", contexts: ["work"], workRelevant: true },
  { id: "q23", text: "あなたは社交的な交流がストレスを軽減する効果的な方法だと考えています。", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q24", text: "外部からの刺激が多すぎると、圧倒されてしまいます。", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q25", text: "あなたは聞くよりも表現する傾向があります。", dimension: "EI", agree: "E", contexts: ["general"] },
  { id: "q26", text: "あなたは思慮深く、意見を言うことに熱心ではありません。", dimension: "EI", agree: "I", contexts: ["general"] },
  { id: "q27", text: "あなたは、事前にすべてを計画するよりも、実際に行動して考えることを好みます。", dimension: "EI", agree: "E", contexts: ["personal"] },
  { id: "q28", text: "あなたは、大規模なグループでのやり取りよりも 1 対 1 のコミュニケーションを好みます。", dimension: "EI", agree: "I", contexts: ["personal"] },
  { id: "q29", text: "人前では、あなたは通常、自信を持ってよくしゃべります。", dimension: "EI", agree: "E", contexts: ["general"] },
  { id: "q30", text: "自分の考えを整理するために一人になる時間が必要になることがよくあります。", dimension: "EI", agree: "I", contexts: ["personal"] },

  // SN (30 questions) - Sensing (S) vs Intuition (N)
  { id: "q31", text: "あなたは細部に細心の注意を払い、環境の変化に気づきます。", dimension: "SN", agree: "S", contexts: ["work"], workRelevant: true },
  { id: "q32", text: "あなたはより深い意味や将来の可能性にもっと焦点を当てます。", dimension: "SN", agree: "N", contexts: ["general"] },
  { id: "q33", text: "あなたは抽象的な理論よりも、具体的で観察可能な事実を扱うことを好みます。", dimension: "SN", agree: "S", contexts: ["work"], workRelevant: true },
  { id: "q34", text: "あなたは想像力豊かで創造的なアイデアを持っていることがよくあります。", dimension: "SN", agree: "N", contexts: ["general"] },
  { id: "q35", text: "過去の経験を信頼し、確立された手順に従う傾向があります。", dimension: "SN", agree: "S", contexts: ["general"] },
  { id: "q36", text: "固定観念を簡単に打ち破り、新しい方法を試します。", dimension: "SN", agree: "N", contexts: ["work"], workRelevant: true },
  { id: "q37", text: "あなたは空想の中で生きる人よりも現実的な人を好みます。", dimension: "SN", agree: "S" },
  { id: "q38", text: "哲学やシンボル、将来のビジョンなどに強い興味を感じることが多いです。", dimension: "SN", agree: "N" },
  { id: "q39", text: "あなたは、現在の現実に焦点を当てて、現在に生きる傾向があります。", dimension: "SN", agree: "S" },
  { id: "q40", text: "兆候がなくても、物事がどのように展開するかを予測できます。", dimension: "SN", agree: "N" },
  { id: "q41", text: "あなたは明確な指示と具体的な実行計画を好みます。", dimension: "SN", agree: "S" },
  { id: "q42", text: "日常的で繰り返しの仕事は非常に退屈にさせます。", dimension: "SN", agree: "N" },
  { id: "q43", text: "あなたは証拠やデータを重視し、根拠のない憶測を嫌います。", dimension: "SN", agree: "S" },
  { id: "q44", text: "あなたは比喩や連想を使って自分の意見を表現することを好みます。", dimension: "SN", agree: "N" },
  { id: "q45", text: "あなたは、先見の明があることよりも現実的であることが重要だと考えています。", dimension: "SN", agree: "S" },
  { id: "q46", text: "あなたは、非現実的な「もしも」の可能性について考えることがよくあります。", dimension: "SN", agree: "N" },
  { id: "q47", text: "あなたは事実の正確さを、時には厳格に重視します。", dimension: "SN", agree: "S" },
  { id: "q48", text: "たとえ非論理的に見えても、インスピレーションや直感を大切にします。", dimension: "SN", agree: "N" },
  { id: "q49", text: "人生に直接応用できるスキルを学ぶことが好きです。", dimension: "SN", agree: "S" },
  { id: "q50", text: "たとえすぐには役に立たなくても、複雑な理論を探求することが好きです。", dimension: "SN", agree: "N" },
  { id: "q51", text: "複雑なデバイスをマニュアルに従って操作することを好みます。", dimension: "SN", agree: "S" },
  { id: "q52", text: "断片的な情報から全体像をつなぎ合わせることができます。", dimension: "SN", agree: "N" },
  { id: "q53", text: "あなたは、マクロレベルの計画を立てるよりも、日々の雑務を処理することを好みます。", dimension: "SN", agree: "S" },
  { id: "q54", text: "現在の成果よりも、将来の可能性の方があなたを興奮させます。", dimension: "SN", agree: "N" },
  { id: "q55", text: "あなたは物事の具体的な外観や詳細を説明する傾向があります。", dimension: "SN", agree: "S" },
  { id: "q56", text: "あなたはつながりや隠れたパターンを探す傾向があります。", dimension: "SN", agree: "N" },
  { id: "q57", text: "あなたは斬新ではあるが証明されていない理論に懐疑的です。", dimension: "SN", agree: "S" },
  { id: "q58", text: "あなたは自分の考え方が他の人よりも先を行っていると感じることがよくあります。", dimension: "SN", agree: "N" },
  { id: "q59", text: "あなたは段階的な指導方法を好みます。", dimension: "SN", agree: "S" },
  { id: "q60", text: "あなたは飛躍的な思考を好み、予期せぬ角度から発見することがよくあります。", dimension: "SN", agree: "N" },

  // TF (30 questions) - Thinking (T) vs Feeling (F)
  { id: "q61", text: "意思決定を行うときは、まず論理と客観的事実を考慮します。", dimension: "TF", agree: "T" },
  { id: "q62", text: "意思決定をするときは、まず他人の感情や価値観を考慮します。", dimension: "TF", agree: "F" },
  { id: "q63", text: "あなたは、調和や思いやりよりも公平性や客観性の方が重要だと考えています。", dimension: "TF", agree: "T" },
  { id: "q64", text: "あなたは対人関係の調和を保つために進んで妥協します。", dimension: "TF", agree: "F" },
  { id: "q65", text: "他人を批判するときは、感情を持たずに直接間違いを指摘します。", dimension: "TF", agree: "T" },
  { id: "q66", text: "他人を批判するとき、あなたは彼らの感情を傷つけないように賢明です。", dimension: "TF", agree: "F" },
  { id: "q67", text: "プロセスにおける感情的な経験よりも、結果と効率を重視します。", dimension: "TF", agree: "T" },
  { id: "q68", text: "あなたは、他人を気遣い、感情を読み取ることが最も重要な資質であると信じています。", dimension: "TF", agree: "F" },
  { id: "q69", text: "ディベートでは、相手が気まずく感じないかどうかよりも、論理的な厳密さを重視します。", dimension: "TF", agree: "T" },
  { id: "q70", text: "あなたは物語や他人の経験に触れると簡単に感動します。", dimension: "TF", agree: "F" },
  { id: "q71", text: "あなたはルールや基準に従って公平に行動することを好みます。", dimension: "TF", agree: "T" },
  { id: "q72", text: "あなたは、ルールは柔軟で、特定の状況において他の人に配慮すべきだと考えています。", dimension: "TF", agree: "F" },
  { id: "q73", text: "感情が判断力に影響を与える人々を理解するのは難しいと感じます。", dimension: "TF", agree: "T" },
  { id: "q74", text: "あなたはよく他人の立場に立って考えます。", dimension: "TF", agree: "F" },
  { id: "q75", text: "あなたは合理性が問題を解決する唯一の正しい方法だと信じています。", dimension: "TF", agree: "T" },
  { id: "q76", text: "あなたは仕事でも生活でも共感が重要だと信じています。", dimension: "TF", agree: "F" },
  { id: "q77", text: "たとえ受け入れがたい事実であっても、ありのままに伝えてしまう傾向があります。", dimension: "TF", agree: "T" },
  { id: "q78", text: "他人を傷つけないために、あなたは「真っ白な嘘」を選択することがあります。", dimension: "TF", agree: "F" },
  { id: "q79", text: "あなたは、冷静で合理的、そして少し冷淡な人を好みます。", dimension: "TF", agree: "T" },
  { id: "q80", text: "あなたは、温かく、熱心で、理解のある人を好みます。", dimension: "TF", agree: "F" },
  { id: "q81", text: "複雑な問題を分析することに非常にやりがいを感じます。", dimension: "TF", agree: "T" },
  { id: "q82", text: "あなたは、感情的な問題を抱えている人を助けることに意義があると感じています。", dimension: "TF", agree: "F" },
  { id: "q83", text: "職場では、個人的な感情ではなく、業績に基づいて報酬と罰を与えることを好みます。", dimension: "TF", agree: "T" },
  { id: "q84", text: "職場では、チームの結束力やメンバーの気分も同様に重要だと考えています。", dimension: "TF", agree: "F" },
  { id: "q85", text: "あなたは科学と論理で世界のすべてを説明できると信じています。", dimension: "TF", agree: "T" },
  { id: "q86", text: "あなたは、いくつかのこと（愛や信仰など）は論理では測れないと信じています。", dimension: "TF", agree: "F" },
  { id: "q87", text: "あなたは頭の中で厳密な論理的枠組みを構築する傾向があります。", dimension: "TF", agree: "T" },
  { id: "q88", text: "あなたは、他人が自分をどう認識しているか、そして自分の好感度をとても気にしています。", dimension: "TF", agree: "F" },
  { id: "q89", text: "あなたは心理学や芸術よりも論理や数学を好みます。", dimension: "TF", agree: "T" },
  { id: "q90", text: "あなたは他人の感情の変化に簡単に気づきます。", dimension: "TF", agree: "F" },

  // JP (30 questions) - Judging (J) vs Perceiving (P)
  { id: "q91", text: "あなたは事前に計画を立て、スケジュールに厳密に従うことを好みます。", dimension: "JP", agree: "J" },
  { id: "q92", text: "あなたは流れに身を任せ、計画を柔軟に保つことを好みます。", dimension: "JP", agree: "P" },
  { id: "q93", text: "タスクを開始する前に、通常は机と環境を整理します。", dimension: "JP", agree: "J" },
  { id: "q94", text: "あなたは人生のルールや境界があなたの自由と創造性を制限していると感じています。", dimension: "JP", agree: "P" },
  { id: "q95", text: "締め切り近くになるよりも早くタスクを完了する傾向があります。", dimension: "JP", agree: "J" },
  { id: "q96", text: "プレッシャーがかかると（締め切りが迫っているなど）、パフォーマンスが向上することがよくあります。", dimension: "JP", agree: "P" },
  { id: "q97", text: "あなたは整然とした環境を好み、混乱を許容しません。", dimension: "JP", agree: "J" },
  { id: "q98", text: "新しい興味やプロジェクトを始めても、最後までやり続けるのは難しいことがよくあります。", dimension: "JP", agree: "P" },
  { id: "q99", text: "あなたは物事を結論に導くことを好み、未解決の状態を嫌います。", dimension: "JP", agree: "J" },
  { id: "q100", text: "複数の選択肢を残しておき、最後の瞬間に決定することを好みます。", dimension: "JP", agree: "P" },
  { id: "q101", text: "通常、チケットを予約するか、事前に予約をします。", dimension: "JP", agree: "J" },
  { id: "q102", text: "あなたは驚きと不確実性に満ちた旅行が好きです。", dimension: "JP", agree: "P" },
  { id: "q103", text: "あなたは規律が成功の基礎であると信じています。", dimension: "JP", agree: "J" },
  { id: "q104", text: "決まったプロセスに従うよりも、自由に働くことを好みます。", dimension: "JP", agree: "P" },
  { id: "q105", text: "あなたはいつも物を元の場所に戻します。", dimension: "JP", agree: "J" },
  { id: "q106", text: "部屋や机の上はたいてい少し散らかっていますが、散らかった中に物が見つかることもあります。", dimension: "JP", agree: "P" },
  { id: "q107", text: "あなたはコントロールすることを好み、予期せぬ状況を嫌います。", dimension: "JP", agree: "J" },
  { id: "q108", text: "あなたは計画性よりも適応力の方が重要だと考えています。", dimension: "JP", agree: "P" },
  { id: "q109", text: "一度下した決定を変更しない傾向があります。", dimension: "JP", agree: "J" },
  { id: "q110", text: "新しい発見やインスピレーションに基づいて考えが変わることがよくあります。", dimension: "JP", agree: "P" },
  { id: "q111", text: "あなたはとても責任感があり、信頼できる人です。", dimension: "JP", agree: "J" },
  { id: "q112", text: "変化に計画が追いつかないと感じて、計画を立てなくなることがよくあります。", dimension: "JP", agree: "P" },
  { id: "q113", text: "あなたは生活と仕事を明確に分けておくことを好みます。", dimension: "JP", agree: "J" },
  { id: "q114", text: "一度に複数のタスクを実行すると、それが面白いと感じることがよくあります。", dimension: "JP", agree: "P" },
  { id: "q115", text: "あなたは、物事をより効率的かつ制御可能にするためにルールが存在すると信じています。", dimension: "JP", agree: "J" },
  { id: "q116", text: "あなたは「気楽な人」または「遊び好き」な人だと思われることが多いです。", dimension: "JP", agree: "P" },
  { id: "q117", text: "To Do リストから項目をチェックする感覚が好きです。", dimension: "JP", agree: "J" },
  { id: "q118", text: "最終的な結果に焦点を当てるよりも、プロセスを探索することを好みます。", dimension: "JP", agree: "P" },
  { id: "q119", text: "あなたは体系的で段階的な作業を好みます。", dimension: "JP", agree: "J" },
  { id: "q120", text: "あなたは未知の分野や曖昧な分野を探索することを好みます。", dimension: "JP", agree: "P" },
]
