import { type Question } from './mbti-types'

export const QUESTIONS: Question[] = [
  // EI (30 questions) - Extraversion (E) vs Introversion (I)
  { id: "q1", text: "In social settings, you are usually active and initiate conversations.", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q2", text: "You prefer to think alone rather than discuss loudly in groups.", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q3", text: "Long social activities energize you rather than exhaust you.", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q4", text: "You tend to fully formulate what you want to say in your head before speaking.", dimension: "EI", agree: "I", contexts: ["social", "personal"], socialRelevant: true },
  { id: "q5", text: "You like being the center of attention.", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q6", text: "At parties, you prefer deep talks with a few people you know.", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q7", text: "You prefer open office environments to communicate easily with colleagues.", dimension: "EI", agree: "E", contexts: ["work"], workRelevant: true },
  { id: "q8", text: "At work, you prefer a quiet, independent, undisturbed space.", dimension: "EI", agree: "I", contexts: ["work"], workRelevant: true },
  { id: "q9", text: "You usually make new friends easily.", dimension: "EI", agree: "E", contexts: ["general"] },
  { id: "q10", text: "You find solitude enjoyable, even recharging.", dimension: "EI", agree: "I", contexts: ["general"] },
  { id: "q11", text: "You tend to stand out in groups.", dimension: "EI", agree: "E", contexts: ["personal"] },
  { id: "q12", text: "You prefer communicating via text (email or messages) rather than by phone.", dimension: "EI", agree: "I", contexts: ["personal"] },
  { id: "q13", text: "You like participating in lively projects and gain energy from them.", dimension: "EI", agree: "E", contexts: ["work", "social"], workRelevant: true, socialRelevant: true },
  { id: "q14", text: "You often need time to adapt to new social environments.", dimension: "EI", agree: "I", contexts: ["work", "social"], workRelevant: true, socialRelevant: true },
  { id: "q15", text: "You like moving around at gatherings to meet different people.", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q16", text: "You usually do not initiate small talk.", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q17", text: "You enjoy sharing your thoughts and experiences.", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q18", text: "You tend to keep personal privacy, opening up to only a few.", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q19", text: "You find fast-paced, highly interactive environments very appealing.", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q20", text: "You enjoy deep thinking, even if it makes you seem a bit quiet.", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q21", text: "You like leading discussions in a team.", dimension: "EI", agree: "E", contexts: ["work", "social"], workRelevant: true, socialRelevant: true },
  { id: "q22", text: "You prefer working behind the scenes and not being noticed.", dimension: "EI", agree: "I", contexts: ["work"], workRelevant: true },
  { id: "q23", text: "You find socializing an effective way to relieve stress.", dimension: "EI", agree: "E", contexts: ["social"], socialRelevant: true },
  { id: "q24", text: "Too much external stimulation makes you feel overwhelmed.", dimension: "EI", agree: "I", contexts: ["social"], socialRelevant: true },
  { id: "q25", text: "You tend to express rather than listen.", dimension: "EI", agree: "E", contexts: ["general"] },
  { id: "q26", text: "You are thoughtful and not eager to voice opinions.", dimension: "EI", agree: "I", contexts: ["general"] },
  { id: "q27", text: "You like to think in action rather than plan everything beforehand.", dimension: "EI", agree: "E", contexts: ["personal"] },
  { id: "q28", text: "You prefer one-on-one communication over large-group interactions.", dimension: "EI", agree: "I", contexts: ["personal"] },
  { id: "q29", text: "In public, you are usually confident and talkative.", dimension: "EI", agree: "E", contexts: ["general"] },
  { id: "q30", text: "You often need time alone to organize your thoughts.", dimension: "EI", agree: "I", contexts: ["personal"] },

  // SN (30 questions) - Sensing (S) vs Intuition (N)
  { id: "q31", text: "You pay close attention to details and notice changes in the environment.", dimension: "SN", agree: "S", contexts: ["work"], workRelevant: true },
  { id: "q32", text: "You focus more on deeper meanings and future possibilities.", dimension: "SN", agree: "N", contexts: ["general"] },
  { id: "q33", text: "You prefer dealing with concrete, observable facts rather than abstract theory.", dimension: "SN", agree: "S", contexts: ["work"], workRelevant: true },
  { id: "q34", text: "You often have imaginative, creative ideas.", dimension: "SN", agree: "N", contexts: ["general"] },
  { id: "q35", text: "You trust past experience and tend to follow established steps.", dimension: "SN", agree: "S", contexts: ["general"] },
  { id: "q36", text: "You easily break out of fixed thinking and try new methods.", dimension: "SN", agree: "N", contexts: ["work"], workRelevant: true },
  { id: "q37", text: "You prefer practical people rather than those who live in fantasy.", dimension: "SN", agree: "S" },
  { id: "q38", text: "You often feel strong interest in philosophy, symbols, or future visions.", dimension: "SN", agree: "N" },
  { id: "q39", text: "You tend to live in the present, focusing on current reality.", dimension: "SN", agree: "S" },
  { id: "q40", text: "You can foresee how things may develop even without signs.", dimension: "SN", agree: "N" },
  { id: "q41", text: "You like clear instructions and concrete execution plans.", dimension: "SN", agree: "S" },
  { id: "q42", text: "Routine and repetitive work makes you extremely bored.", dimension: "SN", agree: "N" },
  { id: "q43", text: "You care about evidence and data and dislike baseless speculation.", dimension: "SN", agree: "S" },
  { id: "q44", text: "You like to express your views with metaphors or associations.", dimension: "SN", agree: "N" },
  { id: "q45", text: "You think being down-to-earth is more important than being visionary.", dimension: "SN", agree: "S" },
  { id: "q46", text: "You often think about impractical 'what if' possibilities.", dimension: "SN", agree: "N" },
  { id: "q47", text: "You value factual accuracy, sometimes to a rigid degree.", dimension: "SN", agree: "S" },
  { id: "q48", text: "You value inspiration and intuition even if they seem illogical.", dimension: "SN", agree: "N" },
  { id: "q49", text: "You like learning skills that can be directly applied in life.", dimension: "SN", agree: "S" },
  { id: "q50", text: "You like exploring complex theories even if they have no immediate use.", dimension: "SN", agree: "N" },
  { id: "q51", text: "You prefer operating complex devices by following the manual.", dimension: "SN", agree: "S" },
  { id: "q52", text: "You can piece together the big picture from fragmented information.", dimension: "SN", agree: "N" },
  { id: "q53", text: "You prefer handling daily chores rather than doing macro-level planning.", dimension: "SN", agree: "S" },
  { id: "q54", text: "Future possibilities excite you more than current achievements.", dimension: "SN", agree: "N" },
  { id: "q55", text: "You tend to describe the specific appearance and details of things.", dimension: "SN", agree: "S" },
  { id: "q56", text: "You tend to look for connections and hidden patterns.", dimension: "SN", agree: "N" },
  { id: "q57", text: "You are skeptical of novel but unproven theories.", dimension: "SN", agree: "S" },
  { id: "q58", text: "You often feel your thinking is ahead of most people.", dimension: "SN", agree: "N" },
  { id: "q59", text: "You prefer step-by-step teaching methods.", dimension: "SN", agree: "S" },
  { id: "q60", text: "You like leapfrog thinking and often find unexpected angles.", dimension: "SN", agree: "N" },

  // TF (30 questions) - Thinking (T) vs Feeling (F)
  { id: "q61", text: "When making decisions, you first consider logic and objective facts.", dimension: "TF", agree: "T" },
  { id: "q62", text: "When making decisions, you first consider others' feelings and values.", dimension: "TF", agree: "F" },
  { id: "q63", text: "You think fairness and objectivity are more important than harmony and compassion.", dimension: "TF", agree: "T" },
  { id: "q64", text: "You are willing to compromise to maintain interpersonal harmony.", dimension: "TF", agree: "F" },
  { id: "q65", text: "When criticizing others, you point out mistakes directly without emotion.", dimension: "TF", agree: "T" },
  { id: "q66", text: "When criticizing others, you are tactful to avoid hurting their feelings.", dimension: "TF", agree: "F" },
  { id: "q67", text: "You value results and efficiency more than emotional experience in the process.", dimension: "TF", agree: "T" },
  { id: "q68", text: "You believe caring for others and reading emotions is the most important quality.", dimension: "TF", agree: "F" },
  { id: "q69", text: "In debates, you care more about logical rigor than whether the other person feels awkward.", dimension: "TF", agree: "T" },
  { id: "q70", text: "You are easily moved by touching stories or others' experiences.", dimension: "TF", agree: "F" },
  { id: "q71", text: "You prefer to act according to rules and standards, staying impartial.", dimension: "TF", agree: "T" },
  { id: "q72", text: "You think rules should be flexible and considerate of others in specific situations.", dimension: "TF", agree: "F" },
  { id: "q73", text: "You find it hard to understand people whose emotions affect their judgment.", dimension: "TF", agree: "T" },
  { id: "q74", text: "You often put yourself in others' shoes.", dimension: "TF", agree: "F" },
  { id: "q75", text: "You believe rationality is the only correct way to solve problems.", dimension: "TF", agree: "T" },
  { id: "q76", text: "You believe empathy is important in both work and life.", dimension: "TF", agree: "F" },
  { id: "q77", text: "Even if the truth is hard to accept, you tend to tell it as it is.", dimension: "TF", agree: "T" },
  { id: "q78", text: "To avoid hurting others, you sometimes choose a 'white lie'.", dimension: "TF", agree: "F" },
  { id: "q79", text: "You prefer people who are calm, rational, and even a bit cold.", dimension: "TF", agree: "T" },
  { id: "q80", text: "You prefer people who are warm, enthusiastic, and understanding.", dimension: "TF", agree: "F" },
  { id: "q81", text: "You find analyzing complex problems very rewarding.", dimension: "TF", agree: "T" },
  { id: "q82", text: "You find helping others with emotional troubles meaningful.", dimension: "TF", agree: "F" },
  { id: "q83", text: "At work, you prefer rewards and punishments based on performance, not personal feelings.", dimension: "TF", agree: "T" },
  { id: "q84", text: "At work, you believe team cohesion and members' moods are just as important.", dimension: "TF", agree: "F" },
  { id: "q85", text: "You believe science and logic can explain everything in the world.", dimension: "TF", agree: "T" },
  { id: "q86", text: "You believe some things (like love and faith) cannot be measured by logic.", dimension: "TF", agree: "F" },
  { id: "q87", text: "You tend to build rigorous logical frameworks in your mind.", dimension: "TF", agree: "T" },
  { id: "q88", text: "You care a lot about how others perceive you and your likability.", dimension: "TF", agree: "F" },
  { id: "q89", text: "You prefer logic or math over psychology or art.", dimension: "TF", agree: "T" },
  { id: "q90", text: "You easily notice changes in others' emotions.", dimension: "TF", agree: "F" },

  // JP (30 questions) - Judging (J) vs Perceiving (P)
  { id: "q91", text: "You like to plan ahead and strictly follow schedules.", dimension: "JP", agree: "J" },
  { id: "q92", text: "You prefer to go with the flow and keep plans flexible.", dimension: "JP", agree: "P" },
  { id: "q93", text: "Before starting a task, you usually tidy your desk and environment.", dimension: "JP", agree: "J" },
  { id: "q94", text: "You feel life's rules and boundaries limit your freedom and creativity.", dimension: "JP", agree: "P" },
  { id: "q95", text: "You tend to finish tasks early rather than near the deadline.", dimension: "JP", agree: "J" },
  { id: "q96", text: "Under pressure (e.g., a looming deadline), you often perform better.", dimension: "JP", agree: "P" },
  { id: "q97", text: "You like orderly environments and cannot tolerate mess.", dimension: "JP", agree: "J" },
  { id: "q98", text: "You often start new interests or projects but find it hard to stick to the end.", dimension: "JP", agree: "P" },
  { id: "q99", text: "You like to bring things to a conclusion and dislike unresolved states.", dimension: "JP", agree: "J" },
  { id: "q100", text: "You like to keep multiple options open and decide at the last moment.", dimension: "JP", agree: "P" },
  { id: "q101", text: "You usually book tickets or make reservations in advance.", dimension: "JP", agree: "J" },
  { id: "q102", text: "You like travel full of surprises and uncertainty.", dimension: "JP", agree: "P" },
  { id: "q103", text: "You believe discipline is the foundation of success.", dimension: "JP", agree: "J" },
  { id: "q104", text: "You prefer working freely rather than following fixed processes.", dimension: "JP", agree: "P" },
  { id: "q105", text: "You always put things back in their place.", dimension: "JP", agree: "J" },
  { id: "q106", text: "Your room or desk is usually a bit messy, but you can find things in the mess.", dimension: "JP", agree: "P" },
  { id: "q107", text: "You like to be in control and dislike unexpected situations.", dimension: "JP", agree: "J" },
  { id: "q108", text: "You think adaptability is more important than planning ability.", dimension: "JP", agree: "P" },
  { id: "q109", text: "You tend not to change decisions once made.", dimension: "JP", agree: "J" },
  { id: "q110", text: "You often change your mind based on new discoveries or inspiration.", dimension: "JP", agree: "P" },
  { id: "q111", text: "You are a very responsible and reliable person.", dimension: "JP", agree: "J" },
  { id: "q112", text: "You often feel plans can't keep up with changes, so you don't plan.", dimension: "JP", agree: "P" },
  { id: "q113", text: "You like to keep life and work clearly separated.", dimension: "JP", agree: "J" },
  { id: "q114", text: "You often do several tasks at once and find it interesting.", dimension: "JP", agree: "P" },
  { id: "q115", text: "You believe rules exist to make things more efficient and controllable.", dimension: "JP", agree: "J" },
  { id: "q116", text: "You are often seen as an 'easygoing' or 'playful' person.", dimension: "JP", agree: "P" },
  { id: "q117", text: "You like the feeling of checking items off a to-do list.", dimension: "JP", agree: "J" },
  { id: "q118", text: "You prefer exploring the process rather than focusing on the final result.", dimension: "JP", agree: "P" },
  { id: "q119", text: "You prefer systematic, step-by-step work.", dimension: "JP", agree: "J" },
  { id: "q120", text: "You prefer exploring unknown or ambiguous fields.", dimension: "JP", agree: "P" },
]
